version: "3.9"

services:
  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/productdb
      SPRING_DATASOURCE_USERNAME: ---
      SPRING_DATASOURCE_PASSWORD: ---
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: my-topic
#    depends_on:
#      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
